       <div class="leagueitem">


            <div class="logo">
                <img width="100" src="https://www.football-data.org/assets/{logo}.png" />
            </div>

            <div class="label">
                <div class="title">{name}</div>

                <div class="country">
                    {country}
                    <img valign="middle" width="32" src="https://www.football-data.org/assets/{countrycode}.svg" />
                </div>
            </div>
             <div class="ui">
                 <div class="activebtn activebtn{active}">
                     <a class="on" href="{onofflink}">
                         <div>
                             <span>ON</span>
                         </div>
                     </a>
                     <a class="off" href="{onofflink}">
                         <div>
                             <span>OFF</span>
                         </div>
                     </a>
                 </div>
                <a class="details" href="{detailslink}">
                    <div>
                        <span>Details</span>
                    </div>
                </a>
            </div>
        </div>
